Repository WildCodeSchool/orleans-0218-cameleon, pull requests merged in 2018-04, with the labels that each got.

#3 1-0-Project initialisation (CSS+twig)
  public/assets/css/styles.css
  public/assets/fonts/29849_PlazaITC-Normal.ttf
  src/View/layout.html.twig
  src/View/main/index.html.twig
Labels: Correction Done, Reviewed By PO

#19 1 1 affichage navbar
  public/assets/css/navbar.css
  public/assets/images/logo_cameleon.jpg
  public/assets/images/logo_cameleon.png
  public/assets/js/bootstrap.js
  public/assets/js/bootstrap.min.js
  public/assets/js/jquery.js
  src/View/include/navbar.html.twig
  src/View/layout.html.twig
  src/View/main/body.html.twig
Labels: Change Requested, Correction Done

#55 2 14 carte lieux
  public/assets/css/place.css
  public/assets/css/places.css
  public/assets/js/place.js
  src/Controller/PlaceController.php
  src/View/layout.html.twig
  src/View/place/list.html.twig
Labels: Correction Done, Reviewed By PO

#53 2 31 affichage slider
  src/Controller/MainController.php
  src/Model/Slider.php
  src/Model/SliderManager.php
  src/View/main/index.html.twig
  src/View/main/slider.html.twig
Labels: Change Requested, Correction Done

#54 2 31 bandeau annonce
  src/Controller/MainController.php
  src/Model/AbstractManager.php
  src/Model/Alert.php
  src/Model/AlertManager.php
  src/View/main/alert.html.twig
  src/View/main/body.html.twig
  src/View/main/index.html.twig
Labels: Correction Done

#30 1 26 footer
  .gitignore
  app/db.php.dist
  public/assets/css/styles.css
  public/assets/images/face.jpg
  public/assets/images/facebook2.png
  public/assets/images/instagram2.png
  public/assets/images/twitter2.png
  public/index.php
  src/View/include/footer.html.twig
Labels: Correction Done, Reviewed By PO

#56 general merge corrections
  public/assets/css/styles.css
  src/View/include/navbar.html.twig
  src/View/place/list.html.twig
Labels: Reviewed By PO

#58 fix for master
  public/assets/css/place.css
  public/assets/images/image1.jpg
  public/assets/images/image2.jpg
  public/assets/images/image3.jpg
  src/Controller/MainController.php
  src/View/main/body.html.twig
Labels: Reviewed By PO

#60 1 11 lecture equipe
  .gitignore
  public/assets/css/styles.css
  src/Controller/MainController.php
  src/View/main/team.html.twig
Labels: Reviewed By PO

#65 3 0 reparation du head dans le body
  src/View/include/navbar.html.twig
  src/View/main/body.html.twig
Labels: Reviewed By PO

#62 3-23-affichage menu
  .gitignore
  app/routing.php
  public/assets/css/food.css
  public/assets/css/styles.css
  src/Controller/FoodController.php
  src/Model/Food.php
  src/Model/FoodManager.php
  src/Model/PlaceManager.php
  src/View/food/list.html.twig
  src/View/include/navbar.html.twig
  src/View/layout.html.twig
Labels: Correction Done, Reviewed By PO

#71 2 31 bandeau annonce
  public/assets/css/styles.css
  src/View/main/alert.html.twig
Labels: Reviewed By PO

#69 2 14 carte lieux
  public/assets/css/place.css
  src/View/place/list.html.twig
Labels: Conflicts, Correction Done, Reviewed By PO

#68 2 34 mise en lumiere
  public/assets/css/styles.css
  src/Controller/MainController.php
  src/Model/Spotlight.php
  src/Model/SpotlightManager.php
  src/View/main/index.html.twig
  src/View/main/spotlight.html.twig
Labels: Conflicts, Correction Done, Reviewed By PO

#70 2-33-fil_facebook
  app/Connection.php
  app/config.php
  public/assets/css/footer.css
  public/assets/css/styles.css
  public/assets/js/freme.js
  src/View/include/footer.html.twig
  src/View/main/body.html.twig
Labels: Conflicts, Correction Done

#73 2 31 bandeau annonce
  public/assets/css/styles.css
  src/View/main/alert.html.twig
Labels: Conflicts, Correction Done, Reviewed By PO

#78 fix for presentation
  app/routing.php
  src/Model/FoodManager.php
  src/View/main/team.html.twig
Labels: Reviewed By PO

#79 Dev
  .gitignore
  app/Connection.php
  app/config.php
  app/routing.php
  public/assets/css/food.css
  public/assets/css/footer.css
  public/assets/css/place.css
  public/assets/css/styles.css
  public/assets/js/freme.js
  src/Controller/AdminController.php
  src/Controller/FoodController.php
  src/Controller/MainController.php
  src/Model/Food.php
  src/Model/FoodManager.php
  src/Model/PlaceManager.php
  src/Model/Spotlight.php
  src/Model/SpotlightManager.php
  src/View/admin/body.html.twig
  src/View/admin/index.html.twig
  src/View/admin/place.html.twig
  src/View/food/list.html.twig
  src/View/include/footer.html.twig
  src/View/include/navbar.html.twig
  src/View/layout.html.twig
  src/View/main/alert.html.twig
  src/View/main/body.html.twig
  src/View/main/index.html.twig
  src/View/main/spotlight.html.twig
  src/View/main/team.html.twig
  src/View/place/list.html.twig
Labels: Reviewed By PO

#80 fix accolade css
  public/assets/css/styles.css
  public/assets/images/john.jpg
Labels: Reviewed By PO

#34 1 10 lecture concept
  .gitignore
  public/assets/css/styles.css
  src/Controller/MainController.php
  src/Model/Company.php
  src/Model/CompanyManager.php
  src/View/main/body.html.twig
  src/View/main/concept.html.twig
  src/View/main/index.html.twig
Labels: Correction Done, Reviewed By PO

#64 2 15 lecture galerie
  public/assets/css/styles.css
  public/assets/images/gallery/image1.jpg
  src/Controller/MainController.php
  src/Model/Gallery.php
  src/Model/GalleryManager.php
  src/View/main/body.html.twig
  src/View/main/gallery.html.twig
  src/View/main/index.html.twig
Labels: Conflicts, Correction Done, Reviewed By PO

#72 2-31 affichage slider
  public/assets/css/styles.css
  src/View/main/slider.html.twig
Labels: Conflicts, Correction Done, Reviewed By PO

#98 3 0 fix css
  public/assets/css/food.css
  public/assets/css/navbar.css
  public/assets/css/place.css
  public/assets/css/styles.css
  public/assets/images/chevron-droit.png
  public/assets/images/chevron-gauche.png
  src/View/food/list.html.twig
  src/View/main/alert.html.twig
  src/View/main/index.html.twig
  src/View/main/team.html.twig
  src/View/place/list.html.twig
Labels: Reviewed By PO

#82 3 6 admin lieux
  app/routing.php
  public/assets/css/styles.css
  src/Controller/AdminController.php
  src/Controller/PlaceAdminController.php
  src/Model/AbstractManager.php
  src/View/admin/body.html.twig
  src/View/admin/index.html.twig
  src/View/admin/place.html.twig
  src/View/layout.html.twig
Labels: Correction Done, Reviewed By PO

#97 3 17 page galerie
  app/routing.php
  public/assets/css/gallery.css
  public/assets/css/styles.css
  public/assets/images/gallery/salade.jpg
  public/assets/images/gallery/sushi.png
  public/assets/images/gallery/tarte.jpg
  public/assets/images/gallery/truck.jpg
  public/assets/images/pattern.jpg
  public/assets/images/pattern.png
  src/Controller/GalleryController.php
  src/Model/Picture.php
  src/Model/PictureManager.php
  src/View/gallery/gallery.html.twig
  src/View/include/navbar.html.twig
Labels: Conflicts, Correction Done, Reviewed By PO

#100 fix spotlight text a gauche et photo plus grande
  public/assets/css/styles.css
  src/View/main/spotlight.html.twig
Labels: Reviewed By PO

#101 modification de la section gallery pour qu'elle utilise la table picture
  public/assets/css/styles.css
  src/Controller/MainController.php
  src/Model/Gallery.php
  src/Model/GalleryManager.php
  src/Model/PictureManager.php
  src/View/main/gallery.html.twig
Labels: Reviewed By PO

#102 fixing css
  public/assets/css/styles.css
Labels: Reviewed By PO

#103 correction responsivité
  src/View/admin/place.html.twig
Labels: Reviewed By PO

#105 4 0 correction navbar admin
  src/View/admin/body.html.twig
Labels: Reviewed By PO

#106 4 6 fix admin places
  src/Controller/PlaceAdminController.php
  src/View/place/list.html.twig
Labels: Correction Done, Reviewed By PO

#107 4 0 fixing police size for phone size
  public/assets/css/food.css
  public/assets/css/footer.css
  public/assets/css/place.css
  public/assets/css/styles.css
Labels: Reviewed By PO

#104 4-40-admin alert
  app/routing.php
  public/assets/css/navbar.css
  public/assets/css/styles.css
  public/index.php
  src/Controller/HeaderAdminController.php
  src/Controller/PlaceAdminController.php
  src/Structures/Notification.php
  src/Structures/Session.php
  src/View/admin/body.html.twig
  src/View/admin/header.html.twig
Labels: Correction Done

#111 Dev for presentation 2
  .gitignore
  app/routing.php
  public/assets/css/food.css
  public/assets/css/footer.css
  public/assets/css/gallery.css
  public/assets/css/navbar.css
  public/assets/css/place.css
  public/assets/css/styles.css
  public/assets/images/chevron-droit.png
  public/assets/images/chevron-gauche.png
  public/assets/images/gallery/image1.jpg
  public/assets/images/gallery/salade.jpg
  public/assets/images/gallery/sushi.png
  public/assets/images/gallery/tarte.jpg
  public/assets/images/gallery/truck.jpg
  public/assets/images/pattern.jpg
  public/assets/images/pattern.png
  public/index.php
  src/Controller/AdminController.php
  src/Controller/GalleryController.php
  src/Controller/HeaderAdminController.php
  src/Controller/MainController.php
  src/Controller/PlaceAdminController.php
  src/Model/AbstractManager.php
  src/Model/Company.php
  src/Model/CompanyManager.php
  src/Model/Picture.php
  src/Model/PictureManager.php
  src/Structures/Notification.php
  src/Structures/Session.php
  src/View/admin/body.html.twig
  src/View/admin/header.html.twig
  src/View/admin/index.html.twig
  src/View/admin/place.html.twig
  src/View/food/list.html.twig
  src/View/gallery/gallery.html.twig
  src/View/include/navbar.html.twig
  src/View/layout.html.twig
  src/View/main/alert.html.twig
  src/View/main/body.html.twig
  src/View/main/concept.html.twig
  src/View/main/gallery.html.twig
  src/View/main/index.html.twig
  src/View/main/slider.html.twig
  src/View/main/spotlight.html.twig
  src/View/main/team.html.twig
  src/View/place/list.html.twig
Labels: Reviewed By PO

#112 4-6 maj notifications
  src/Controller/PlaceAdminController.php
Labels: Reviewed By PO

#113 3 17 page galerie
  public/assets/css/gallery.css
  public/assets/images/gallery/5ad9b7b9802a2.jpg
  public/assets/images/gallery/5ad9b7ca53a5d.jpg
  public/assets/images/gallery/5ad9b7e1723da.jpg
  public/assets/images/gallery/5ad9b7eb6538c.jpg
  public/assets/images/gallery/5ad9b7f1cfa28.jpg
  public/assets/images/gallery/5ad9b7fbe426d.jpg
  public/assets/images/gallery/5ad9b84a2cb75.jpg
  public/assets/images/gallery/5ad9b870e4000.jpg
  src/View/gallery/gallery.html.twig
Labels: Reviewed By PO

#114 images rondes
  public/assets/css/styles.css
  src/View/main/team.html.twig
Labels: Reviewed By PO

#108 création du formulaire d'image
  app/routing.php
  public/assets/css/admin.css
  public/assets/images/chevron-droit.png
  public/assets/images/chevron-gauche.png
  public/assets/images/face.jpg
  public/assets/images/facebook2.png
  public/assets/images/favicon.png
  public/assets/images/gallery/.gitkeep
  public/assets/images/gallery/image1.jpg
  public/assets/images/gallery/salade.jpg
  public/assets/images/gallery/sushi.png
  public/assets/images/gallery/tarte.jpg
  public/assets/images/gallery/truck.jpg
  public/assets/images/image.jpg
  public/assets/images/image1.jpg
  public/assets/images/image2.jpg
  public/assets/images/image3.jpg
  public/assets/images/instagram2.png
  public/assets/images/john.jpg
  public/assets/images/john.png
  public/assets/images/logo_cameleon.jpg
  public/assets/images/logo_cameleon.png
  public/assets/images/pattern.jpg
  public/assets/images/pattern.png
  public/assets/images/sylvain.jpg
  public/assets/images/twitter2.png
  src/Controller/GalleryAdminController.php
  src/Model/AbstractManager.php
  src/View/admin/body.html.twig
  src/View/admin/gallery.html.twig
Labels: Conflicts, Correction Done, Reviewed By PO

#116 nouvelle présentation de la section galerie
  public/assets/css/styles.css
  src/View/main/gallery.html.twig
Labels: Reviewed By PO

#121 fix slider
  public/assets/css/styles.css
  src/View/main/slider.html.twig
Labels: Reviewed By PO

#122 fix for food
  public/assets/css/food.css
  src/View/food/list.html.twig
Labels: Reviewed By PO

#138 change le hauteur de la footer
  public/assets/css/footer.css
  public/assets/css/styles.css
  public/assets/images/chevron-droit.png
  public/assets/images/chevron-gauche.png
  public/assets/images/facebook2.png
  public/assets/images/favicon.png
  public/assets/images/image.jpg
  public/assets/images/image1.jpg
  public/assets/images/image2.jpg
  public/assets/images/image3.jpg
  public/assets/images/instagram2.png
  public/assets/images/john.jpg
  public/assets/images/john.png
  public/assets/images/logo_cameleon.jpg
  public/assets/images/logo_cameleon.png
  public/assets/images/pattern.jpg
  public/assets/images/pattern.png
  public/assets/images/sylvain.jpg
  public/assets/images/twitter2.png
  src/View/include/footer.html.twig
Labels: Reviewed By PO

#119 ajout de la classe de gestion de fichier
  public/assets/images/gallery/5ad9b870e4000.jpg
  src/Controller/GalleryAdminController.php
  src/Structures/Upload.php
Labels: Correction Done, Reviewed By PO

#141 Couleur du bouton
  public/assets/css/styles.css
Labels: Reviewed By PO

#142 5 40 admin images slider
  app/routing.php
  public/assets/images/slider/bagels.jpg
  public/assets/images/upload/slider/.gitkeep
  public/assets/images/upload/slider/5ae069a3398fe.jpg
  public/assets/images/upload/slider/5ae06adb8db9a.jpg
  src/Controller/HeaderAdminController.php
  src/Structures/Upload.php
  src/View/admin/header.html.twig
  src/View/main/slider.html.twig
Labels: Reviewed By PO

#145 correction de l'input file sur firefox
  public/assets/css/admin.css
  src/View/admin/gallery.html.twig
Labels: Reviewed By PO

#147 5 0 changing css for place page
  public/assets/css/place.css
  public/assets/css/styles.css
Labels: Reviewed By PO

#139 5 39 admin menu
  app/routing.php
  src/Controller/FoodAdminController.php
  src/Controller/FoodController.php
  src/Model/AbstractManager.php
  src/Model/Category.php
  src/Model/CategoryManager.php
  src/Model/Food.php
  src/Model/FoodManager.php
  src/View/admin/body.html.twig
  src/View/admin/food.html.twig
  src/View/admin/showCategory.html.twig
  src/View/admin/showNewCategory.html.twig
  src/View/admin/showNewProduct.html.twig
  src/View/admin/showProduct.html.twig
Labels: Correction Done, Reviewed By PO

#148 add API for coordinates
  public/assets/js/place.js
  src/View/admin/place.html.twig
Labels: Reviewed By PO

#149 fixing navbar border
  public/assets/css/navbar.css
Labels: Reviewed By PO

#150 retouches css
  public/assets/css/styles.css
Labels: Reviewed By PO

#126 formulair admin team
  app/routing.php
  public/assets/css/styles.css
  public/assets/css/teamAdmin.css
  src/Controller/PlaceAdminController.php
  src/Controller/TeamAdminController.php
  src/Controller/TeamController.php
  src/Model/AbstractManager.php
  src/Model/Team.php
  src/View/admin/body.html.twig
  src/View/admin/place.html.twig
  src/View/admin/team.html.twig
  src/View/main/body.html.twig
Labels: Correction Done, Reviewed By PO

#152 section admin cocept
  app/routing.php
  src/Controller/CompanyAdminController.php
  src/View/admin/company.html.twig
Labels: Reviewed By PO

#156 fix navbar resolution taille des textes et liens
  public/assets/css/navbar.css
  public/assets/css/styles.css
  public/assets/images/upload/spotlight/5ae1ed2f7d20d.jpg
  src/View/include/navbar.html.twig
  src/View/main/team.html.twig
Labels: Conflicts, Correction Done, Reviewed By PO

#158 fix bouton admin food
  app/routing.php
  src/View/admin/food.html.twig
Labels: Correction Done

#160 3 3 admin concept
  public/assets/css/styles.css
  public/assets/js/wysiwyg.js
  src/View/admin/company.html.twig
  src/View/include/footer.html.twig
  src/View/main/concept.html.twig
Labels: Conflicts, Correction Done, Reviewed By PO

#163 fix footer
  src/View/include/footer.html.twig
Labels: Reviewed By PO

#187 correction du bouton parcourir
  public/assets/css/admin.css
Labels: A check, Reviewed By PO
