Repository WildCodeSchool/orleans-0218-cameleon, pull requests merged in 2018-05, with the labels that each got.

#189 Fix footer
  public/assets/css/footer.css
  src/View/admin/food.html.twig
  src/View/include/footer.html.twig
Labels: A check

#199 add coordinate messages
  public/assets/css/styles.css
  public/assets/images/gallery/5ae968a9e0087.jpg
  public/assets/images/upload/slider/5ae968d071514.jpg
  public/assets/js/place.js
  src/View/admin/place.html.twig
Labels: Correction Done, Reviewed By PO

#202 fix footer
  public/assets/css/footer.css
  public/assets/images/gallery/5ae97202b3b83.jpg
  public/assets/images/upload/slider/5ae971d982c57.jpg
  public/assets/images/upload/spotlight/5ae971f389338.jpg
  src/Controller/TeamAdminController.php
Labels: Reviewed By PO

#203 fixing cols
  src/View/main/concept.html.twig
Labels: Reviewed By PO

#217 fix de la navbar
  src/View/include/navbar.html.twig
Labels: Reviewed By PO

#218 Fix title
  public/assets/css/gallery.css
  src/View/gallery/gallery.html.twig
Labels: Reviewed By PO

#219 git ignore for upload
  .gitignore
  public/assets/images/upload/slider/.gitkeep
  public/assets/images/upload/spotlight/.gitkeep
  public/assets/images/upload/spotlight/5ae9aba8e4534.jpg
  public/assets/images/upload/team/.gitkeep
  public/assets/images/upload/team/5ae9ac4b6f1e8.jpg
  public/assets/images/upload/team/5ae9ac51a0ab1.jpg
  src/Controller/GalleryAdminController.php
Labels: Reviewed By PO

#220 Codesniffer
  public/assets/css/footer.css
  public/assets/css/navbar.css
  public/assets/css/styles.css
  src/Controller/FoodAdminController.php
  src/Controller/GalleryAdminController.php
  src/Controller/GalleryController.php
  src/Controller/HeaderAdminController.php
  src/Controller/MainController.php
  src/Controller/PlaceAdminController.php
  src/Controller/PlaceController.php
  src/Controller/SpotlightAdminController.php
  src/Controller/TeamAdminController.php
  src/Model/AbstractManager.php
  src/Model/Alert.php
  src/Model/AlertManager.php
  src/Model/FoodManager.php
  src/Model/Picture.php
  src/Model/PlaceManager.php
  src/Model/Slider.php
  src/Model/SliderManager.php
  src/Structures/Notification.php
  src/Structures/Session.php
  src/View/admin/body.html.twig
  src/View/admin/food.html.twig
  src/View/admin/header.html.twig
  src/View/admin/place.html.twig
  src/View/admin/showProduct.html.twig
  src/View/admin/spotlight.html.twig
  src/View/admin/team.html.twig
  src/View/food/list.html.twig
  src/View/gallery/gallery.html.twig
  src/View/include/footer.html.twig
  src/View/layout.html.twig
  src/View/main/alert.html.twig
  src/View/main/body.html.twig
  src/View/main/concept.html.twig
  src/View/main/gallery.html.twig
  src/View/main/slider.html.twig
  src/View/main/spotlight.html.twig
  src/View/place/list.html.twig
Labels: Reviewed By PO

#221 fix de la navbar sur mobile
  public/assets/css/navbar.css
Labels: Reviewed By PO

#223 gitkeep
  public/assets/images/upload/.gitkeep
Labels: Reviewed By PO
